# Config file for Jekyll website

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-titles-from-headings
- jekyll-relative-links

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

title: MEDICINE
description: Motion Estimation by DIstributional Contrastive Inference for NEurophysiology
