# Config file for Jekyll website

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

title: MEDiCINe
description: Motion Estimation by Distributional Contrastive Inference for Neurophysiology
